<template>
	<main>
		<div class="loading-page" v-if="loading">
			<div class="preloading-text-about-top">
				<div class="about-text" v-for="(preLoadItem, index) in preLoadItems" :key="index">
					<p :id="preLoadItem.id_aka" class="aka move-right">{{ preLoadItem.aka }}</p>
					<p :id="preLoadItem.id_dash" class="dash op-2">{{ preLoadItem.dash }}</p>
					<p :id="preLoadItem.id_name" class="name">{{ preLoadItem.name }}</p>
					<p :id="preLoadItem.id_lastname" class="lastname">{{ preLoadItem.lastname }}</p>
					<p :id="preLoadItem.id_dir" class="dir">{{ preLoadItem.dir }}</p>
					<p :id="preLoadItem.id_cgi" class="cgi">{{ preLoadItem.cgi }}</p>
				</div>
			</div>
			<div class="preloading-text">
				<p>Preloading</p>
				<p>Preloading</p>
				<p>Preloading</p>
				<p>Preloading</p>
				<p>Preloading</p>
			</div>
			<div class="preloading-text-about-buttom">
				<div class="about-text" v-for="(preLoadItem, index) in preLoadItems" :key="index">
					<p :id="preLoadItem.id_aka" class="aka">{{ preLoadItem.aka }}</p>
					<p :id="preLoadItem.id_dash" class="dash">{{ preLoadItem.dash }}</p>
					<p :id="preLoadItem.id_name" class="name">{{ preLoadItem.name }}</p>
					<p :id="preLoadItem.id_lastname" class="lastname">{{ preLoadItem.lastname }}</p>
					<p :id="preLoadItem.id_dir" class="dir">{{ preLoadItem.dir }}</p>
					<p :id="preLoadItem.id_cgi" class="cgi">{{ preLoadItem.cgi }}</p>
				</div>
			</div>
		</div>
	</main>
</template>
  
<script>
export default {
	props: {
		preLoadItems: {
			type: Array,
			default: () => [
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				// TWO ROWS
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				// FOUR ROWS
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				// TWO ROWS
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				// 8 ROWS
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				// TWO ROWS
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				// FOUR ROWS
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				// TWO ROWS
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				{
					id_aka: "aka",
					id_dash: "dash",
					id_name: "name",
					id_lastname: "lastname",
					id_dir: "dir",
					id_cgi: "cgi",
					aka: "HARDLAIT",
					dash: "-",
					name: "NIKOLAS",
					lastname: "ARDELEY",
					dir: "DIRECTOR",
					cgi: "CGI",
				},
				// 8 ROWS
			],
		},
	},
	data: () => ({
		loading: false
	}),
	methods: {
		start() {
			this.loading = true
		},
		finish() {
			this.loading = false
		}
	}
}
</script>
  
<style lang="postcss" scoped>
@keyframes op-1 {
	from {
		opacity: 0;
	}

	to {
		opacity: 1;
	}
}

@keyframes op-2 {
	from {
		opacity: 0;
	}

	to {
		opacity: 1;
	}
}

@keyframes moveLeft {
	from {
		transform: translateX(1920px);
	}

	to {
		transform: translateX(-1920px);
	}
}

.move-right {
	animation-duration: 300ms;
	animation-name: op-1;
	animation-direction: alternate;
}

.op-2 {
	animation-duration: 600ms;
	animation-name: op-2;
	animation-direction: alternate;

}

.move-left {
	animation-duration: 4.5s;
	animation-name: moveLeft;
	animation-iteration-count: infinite;
	animation-direction: alternate;
}

.loading-page {
	display: flex !important;
	align-items: center !important;
	justify-content: space-between !important;
	background-color: var(--bg) !important;
	z-index: 100 !important;
	width: 100vw !important;
	height: 100vh !important;
	flex-direction: column !important;
	position: unset !important;
	top: unset !important;
	left: unset !important;
	text-align: unset !important;
	padding-top: unset !important;
	font-size: unset !important;
	font-family: 'On Diatype Standard' !important;

	& .preloading-text {
		display: flex;
		align-items: center;
		justify-content: space-between;
		width: 100vw;
		padding: .5rem;

		& p {
			margin-top: 0;
		}
	}

	& .preloading-text-about-top,
	& .preloading-text-about-buttom {
		width: 100vw;
		padding: .5rem;
		display: grid;
		grid-template-columns: repeat(6, 1fr);
		overflow-x: hidden;
		max-width: 100%;

		& .about-text {

			display: inline-flex;
			white-space: nowrap;


			& p {
				margin-top: 0;
				margin-right: .5rem;


			}

			& p:nth-child(2n+0) {}

			& p:nth-child(3n+0) {}

			& p:nth-child(4n+0) {}

			& p:nth-child(5n+0) {}

			& p:nth-child(6n+0) {}
		}

	}


}


.loading-page {
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	background: var(--color-primary);
	text-align: center;
	padding-top: 200px;
	font-size: 30px;
	font-family: sans-serif;
	z-index: 100;
}
</style>