site_url: https://hardlait.netlify.app/
logo_url: https://hardlait.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: main
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

allowed_hosts: ['192.168.0.1']

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'projects'
    label: 'Projects'
    label_singular: 'Project'
    folder: 'content/projects'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    preview_path: 'projects/{{slug}}'
    fields:
      - {
          label: 'Created Date',
          name: 'createdAt',
          widget: 'datetime',
          format: 'YYYY',
          date_format: 'YYYY',
          time_format: false,
        }
      - { label: 'Project Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true }

      - {
          label: 'Project Category',
          name: 'category',
          widget: 'select',
          default: 'comercial',
          multiple: true,
          options:
            [
              { label: 'Comercial', value: 'comercial' },
              { label: 'Personal', value: 'personal' },
              { label: 'Other', value: 'other' },
            ],
        }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Intro Description',
          name: 'description',
          widget: 'string',
          required: true,
          pattern: ['.{20,}', 'Short Intro Displayed on Homepage'],
        }
      - { label: 'Cover Image', name: 'cover', widget: 'image', required: true, allow_multiple: false }
      - label: 'HL Layout System'
        name: 'layout_sections'
        widget: 'list'
        minimize_collapsed: true
        types:
          - label: 'Image Grid'
            name: 'image_grid'
            widget: object
            fields:
              - { label: Alt, name: alt, widget: string, default: 'Default Alt Info' }
              - { label: 'Show', name: 'toggle_hide_show', widget: 'boolean', default: true }
              - { label: Template, name: template, widget: string, default: 'image_grid.html' }
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image, max: 9, min: 2 }

          - label: 'Text Block'
            name: 'text_block'
            widget: object
            fields:
              - { label: 'Show', name: 'toggle_hide_show', widget: 'boolean', default: true }
              - { label: Template, name: template, widget: string, default: 'text_block.html' }
              - {
                  label: 'Align Content',
                  name: 'align',
                  widget: 'select',
                  options: ['left', 'center', 'right'],
                  default: 'Center',
                }
              - { label: Text Block, name: text, widget: text, default: 'HL Project XY' }
          - label: 'Full Screen Image'
            name: 'fl_image'
            widget: object
            fields:
              - { label: 'Show', name: 'toggle_hide_show', widget: 'boolean', default: true }
              - { label: Header, name: header, widget: string, default: 'Full Screen Image' }
              - { label: Template, name: template, widget: string, default: 'image_fullscreen.html' }
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image, max: 1, min: 1 }
      - { label: 'Long Project Description', name: 'body', widget: 'markdown', required: false }
      - label: 'Credits'
        name: 'credits'
        widget: 'list'
        summary: '{{fields.quote}} - {{fields.author.name}}'
        fields:
          - { label: Role, name: role, default: 'CGI' }
          - { label: Name, name: name, default: 'Nikolas Hardlait' }
